### ISSUE TITLE
Sometimes episodes don't have URLs

### ISSUE THREAD

**Issue by orthorhombic** [CreamyCookie/pa_to_ap#1]
Thanks for putting this together! I stumbled across it and it has been a big help. 
I found occasionally one podcast in my library (Radiolab) had missing URLs, which I think is due to those items having some non-audio media.

For me, I changed the following:
https://github.com/CreamyCookie/pa_to_ap/blob/3bd5c2ebd3d13ffa523cebd7d0d8d18b87df763b/pa_to_ap.py#L184

to

```python
if MATCH_ON_EPISODE_URL_IF_COULD_NOT_FIND_A_MATCH_OTHERWISE and (ap_url is not None):
```

This seems to have fixed the problem.

**Comment by jgandert** [comment]
Thanks @orthorhombic 

I added that fix
